### ISSUE TITLE
Find the original trigger inside the menu item selection

### ISSUE THREAD

**Issue by sureshviprak** [s-yadav/contextMenu.js#14]
I am not very sure but i didn't find a way to find the original trigger when a menu item is selected for that trigger. I didn't find any example with that feature too. Can you please help me what i can do for it?
I guess the first thing that i would want in context menu selection is the menu item selected & the original element on which this context menu was shown.
Is there anything i missing here?

**Comment by s-yadav** [comment]
Added arguments on function callback which gives reference of trigger and menu. See http://ignitersworld.com/lab/contextMenu.html#inputFormatDoc .
Right now its only available if you pass menu defination as object. Will work on ul li format soon.

**Comment by sureshviprak** [comment]
Thanks a lot for this. I needed for menu structure only for now.
But will look forward to the ul li menu changes too.
Thanks for this awesome library.
