### ISSUE TITLE
Cannot creat a list of menuTrigger that work properly

### ISSUE THREAD

**Issue by yanczhang** [s-yadav/contextMenu.js#15]
I am trying to use the contextMenu plugin to create a list of menuTrigger but could not pass the right ID as a suffix to the menuTrigger or the edit menu ID. e.g.  I have several comments each of which has its own commentID. I need to create a menuTrigger for each comment and also attach the commentID as a suffix to the menuTriggerID and also the li Edit, li delete ID but every time, I only get the last one as the ID suffix to all of the menuTrigger, Edit or Delete ID in my js file when the Edit or delete button clicked although I see the right ID in the html source code. Not sure if the contextMenu is supposed to work in this kind of case. Please guide me if I need to customize the contextMenu.js.

**Comment by s-yadav** [comment]
Hi yanchang,
I am not sure, I understood your query properly, it will be better if you can create a jsfiddle to demonstrate what you want.
If you are asking about how to get information about whuch comment triggered contextMenu you get an data objects in your callback, see http://ignitersworld.com/lab/contextMenu.html#inputFormatDoc (using object for setting up menu).

**Comment by yanczhang** [comment]
what I meant is:
in my jsp page:
  <c:forEach items="${comments}" var="comment" varStatus="rowCounter" >
   <c:set var="cmtID" value="${comment.id}" />
  <div id="menuTrigger_${cmtID}" class="menuTrigger"></div>
                          <ul id="demoMenu_ ${cmtID}"  class="demoMenu">                         
                            <li>
                              <div  id="editCommBtn_${cmtID}" class="editCommBtn">Edit</div>
                            </li>
                              <li>
                              <div id="delCommBtn_${cmtID}" class="delCommBtn">Delete</div>
                            </li>
                               <li>
                                <div id="repCommBtn_${cmtID}" class="repCommBtn">Report</div>                               
                            </li>
</ul>
...
</div>
Then, in my .js file:

 var menuTrgr=$('.menuTrigger'); // note: .menuTrigger is a class, not a single ID

menuTrgr.contextMenu('menu','.demoMenu',{
    displayAround:'trigger'
    //horAdjust:-menuTrgr.width()
});

Do you think the contextMenu is designed for handling this or only just handling single object?

**Comment by s-yadav** [comment]
Ok so it looks like you have multiple list item and separate menu for each item. I am not sure why you have different menus, you can make it work having single menu. Though if there is requirement you can follow given pattern, or similar depending on your requirement

HTML
```html
<ul>
       <li class="menuTrigger" data-menu="menu1"></li>
       <li class="menuTrigger" data-menu="menu2"></li>
</ul>

<ul class="demoMenu"  data-menu="menu1"> ... </ul>
<ul class="demoMenu"  data-menu="menu2"> ... </ul>
```
JS
```javascript
$('.menuTrigger').each(function(){
    var $this = $(this);
     menuTrgr.contextMenu('menu','.demoMenu[data-menu="'+$this.attr('data-menu')+'"]',{ 
             displayAround:'trigger'
             horAdjust: $this.width()
       });
});
```

**Comment by yanczhang** [comment]
Thanks, Sudhanshu. Yes, I did figured it out and it worked. Thanks for your effort to make this plugin.
