### ISSUE TITLE
contextMenu submenus not working in Tablet

### ISSUE THREAD

**Issue by caubia** [s-yadav/contextMenu.js#17]
Hi, 

When you're on a tablet not trigger submenus. Would be able to do with a click.¿ Any way to fix this problem?

Thanks for advance.

Carles.

**Comment by s-yadav** [comment]
Hi, there some work need to be done for fixing touch events properly,
For workaround you can change line 724

```js
         subMenu: function (trigger, selector, baseTrigger, option) {
            trigger.contextMenu('menu', selector, {
                triggerOn: 'hover',
                displayAround: 'trigger',
                position: 'auto',
                baseTrigger: baseTrigger,
                containment: option.containment
            });
        },
 ```

to

```js
         subMenu: function (trigger, selector, baseTrigger, option) {
            trigger.contextMenu('menu', selector, {
                triggerOn: 'mousenter touchend',
                displayAround: 'trigger',
                position: 'auto',
                baseTrigger: baseTrigger,
                containment: option.containment
            });
        },
 ```

Let me know if this solves your problem . Will be having proper fix soon.

**Comment by s-yadav** [comment]
Hi committed v 1.4.0 with touch device support, make sure to update css file also.
let me know if you find any issue with latest build.

**Comment by caubia** [comment]
Sudhanshu,

I tried from the http://ignitersworld.com/lab/contextMenu.html#subMenus page and now works correctly with a smartphone. This afternoon I will try from a tablet. This is great :-).

Just one question, if I want to change the width / height size menu to adapt it to  a smartphone, I should change some css rule?


Thanks !!!

Carles.

**Comment by s-yadav** [comment]
Yes, you should write media queries, just be careful about overflow property, keeping overflow auto/hidden may hide submenus.
