### ISSUE TITLE
I don't cant get the id of original element (LI) that triggered de context menu.

### ISSUE THREAD

**Issue by WBetancur** [s-yadav/contextMenu.js#19]
i have UL with LI elements, and this script 
 var mn2 = [{
        name: 'delete',
        img: 'images/delete.png',
        title: 'to delete this element',
        fun: function (event) {
            alert(event.target.id+' i am delete this element')
        }}]
  $('LI').contextMenu(mn2,{triggerOn:'contextmenu','displayAround': 'trigger'});

but i don't cant get the id of original element (LI) that triggered de context menu.

**Comment by s-yadav** [comment]
Duplicate to #14 , Check http://ignitersworld.com/lab/contextMenu.html#menuParameterDoc,
You will get data and event as parameters in fun method, where you can access the trigger using data.trigger
