### ISSUE TITLE
Custom CSS class namespace option?

### ISSUE THREAD

**Issue by hellocosmin** [s-yadav/contextMenu.js#27]
First of all: very nice plugin, I love that it's lightweight and has lots of options.

Question: would you consider an option for custom class names when instantiating the menu? 

`iw-` is fine for most users, but one might need a custom namespace, in order to have the generated menu classes synced with existing code/namespacing in their app.

Thanks!

**Comment by hellocosmin** [comment]
Whatever, I guess this is not maintained anymore.

Closing this, I gave up on using the plugin when I went through it's code and saw how it adds HTML markup *on page load* for every element that it was triggered on (what if you have a page with 100 elements that you want to use the contextmenu on? you get 100 `<ul>`s injected when you visit the page...)

**Comment by s-yadav** [comment]
@hellocosmin Yes, I know some parts needs a rewrite for better performance. 
But I am quite busy with other priorities this days. Maybe you can contribute here for those changes?
